// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

/** Neon / PgBouncer pooler hostnames must not be used for migrate (advisory locks). */
function isPoolerConnectionString(url: string): boolean {
  return /-pooler[./]/i.test(url) || /[?&]pgbouncer=true/i.test(url);
}

/** Neon pooler URLs use `-pooler` in the hostname; direct host omits that segment. */
function deriveDirectUrlFromNeonPooler(poolerUrl: string): string | null {
  if (!isPoolerConnectionString(poolerUrl)) return null;
  try {
    const parsed = new URL(poolerUrl);
    const directHost = parsed.hostname.replace(/-pooler(?=\.|$)/i, '');
    if (directHost === parsed.hostname) return null;
    parsed.hostname = directHost;
    const href = parsed.toString();
    return href.startsWith('postgres:') && !href.startsWith('postgresql:')
      ? href.replace(/^postgres:/, 'postgresql:')
      : href;
  } catch {
    return null;
  }
}

function isMigrateCliCommand(): boolean {
  return process.argv.some((arg) => /\bmigrate\b/.test(arg));
}

function resolveDatasourceUrl(): string {
  const directUrl = (
    process.env.DIRECT_DB_URL ??
    process.env.DIRECT_URL ??
    ''
  ).trim();

  const databaseUrl = (process.env.DATABASE_URL ?? '').trim();

  // generate / validate / format do not connect; build on Render may only have pooler URL
  if (!isMigrateCliCommand()) {
    return (
      directUrl ||
      databaseUrl ||
      'postgresql://127.0.0.1:5432/joballa_prisma_cli'
    );
  }

  let migrateUrl = directUrl;

  if (!migrateUrl) {
    if (databaseUrl && !isPoolerConnectionString(databaseUrl)) {
      migrateUrl = databaseUrl;
    } else if (databaseUrl && isPoolerConnectionString(databaseUrl)) {
      migrateUrl = deriveDirectUrlFromNeonPooler(databaseUrl) ?? '';
      if (!migrateUrl) {
        throw new Error(
          'Prisma migrate cannot use a pooled DATABASE_URL (Neon -pooler host). ' +
            'On Render, set DIRECT_DB_URL to your Neon *direct* connection string ' +
            '(hostname without -pooler), or use a standard Neon pooler URL so the direct host can be derived. ' +
            'Keep DATABASE_URL as the pooler URL for the app. See helperdocs/RENDER_NEON_DEPLOY.md',
        );
      }
    } else {
      throw new Error(
        'Set DIRECT_DB_URL (Neon direct connection) for prisma migrate deploy. ' +
          'See helperdocs/RENDER_NEON_DEPLOY.md',
      );
    }
  }

  if (isPoolerConnectionString(migrateUrl)) {
    throw new Error(
      'DIRECT_DB_URL must be a direct Postgres URL (no -pooler hostname).',
    );
  }

  return migrateUrl;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    /** Render overlapping deploys / cold Neon can exceed 10s */
    advisoryLockTimeout: 120_000,
  },
  datasource: {
    url: resolveDatasourceUrl(),
  },
});
