-- Employer portal job fields (post job form + preview)
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "neighbourhood" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'XAF';
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "startAsap" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "durationValue" INTEGER;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "durationUnit" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "requiredLevel" TEXT;
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "requirements" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "responsibilities" TEXT[] DEFAULT ARRAY[]::TEXT[];
